const data = [
    {
        productName:"Hettie",
        price:1,
        desc:"hurt prevent major opposite root anybody anywhere wire trunk without develop direction discuss quite pick gas temperature noon account throat collect cat burn something",
        availablity: true,
    },
    {
        productName:"Edna",
        price:2,
        desc:"yesterday boat gate each fresh worker detail race slept choose burst coal simply branch company dirt card happened before printed metal black eventually several",
        availablity: false,
    },
    {
        productName:"Hettie",
        price:658,
        desc:"slow serve earth cut earn pig spell finish gather thee building height find broke escape wood mine hall audience you flew stiff brother ranch",
        availablity: true,
    },
    {
        productName:"Lela",
        price:430,
        desc:"needs valley popular slight we probably harbor month art son day corn detail nobody barn thread which shinning combination policeman count written surrounded boy",
        availablity: false,
    },
    {
        productName:"Harry",
        price:340,
        desc:"instrument shore merely sugar war whenever sides negative might separate wagon rather horse summer rice ancient memory arrive bigger off its degree means simplest",
        availablity: false,
    },
    {
        productName:"Christine",
        price:308,
        desc:"return ready voice elephant important across crowd lady life officer these effect clear welcome film son today ate total progress farm attempt both school",
        availablity: true,
    },
    {
        productName:"Clyde",
        price:816,
        desc:"article important managed honor rock sail wherever welcome mind upper baby dog name tool favorite thin cat zero treated personal enjoy broke copper brick",
        availablity: true,
    },
    {
        productName:"Catherine",
        price:790,
        desc:"now chapter terrible possibly respect characteristic go subject aloud this fly want new work current dish close usual orbit love home salmon policeman shown",
        availablity: true,
    },
    {
        productName:"Rosie",
        price:969,
        desc:"nearer widely hidden needle love dead announced spider friend courage simple came immediately three anything skin know basket father successful floating grabbed vote several",
        availablity: true,
    },
    {
        productName:"Don",
        price:931,
        desc:"early each yes diameter activity tiny gravity poet ear lack power tide flies company goose sitting grow brown truth particles you journey tribe seen",
        availablity: true,
    },
    {
        productName:"Robert",
        price:188,
        desc:"older relationship stay keep spent bear harder separate rays there leaf heavy she possible prove bring struck sugar remain crew headed period deep try",
        availablity: true,
    },
    {
        productName:"Ray",
        price:678,
        desc:"pride corn amount shadow talk rope station larger layers herself nation nearby slow pour bee were aid hay seeing environment slide bet stream important",
        availablity: true,
    },
    {
        productName:"Beulah",
        price:456,
        desc:"ranch independent thus modern realize shorter value promised basket floor habit carefully gate ear adventure label amount wonderful produce aloud basic usual slow problem",
        availablity: true,
    },
    {
        productName:"Louis",
        price:174,
        desc:"jungle cell feathers noon interest trap giant tobacco closely order ran climate careful when aboard cotton pocket funny merely field dull ill ability accident",
        availablity: true,
    },
    {
        productName:"Joseph",
        price:427,
        desc:"brief frozen sharp over like lead hope question eye gun flag famous describe hollow spider forget metal mile level again safe statement property system",
        availablity: true,
    },
    {
        productName:"Eugenia",
        price:493,
        desc:"chest suppose neighbor object consist steep stage tobacco pair lift alone money cage system college recognize western universe offer dead desert current usually mail",
        availablity: true,
    },
    {
        productName:"Dale",
        price:900,
        desc:"anyone why gate member said independent easily younger needle write cloth pig very mission advice sharp running support eight forgotten race neighbor shoe stock",
        availablity: true,
    },
    {
        productName:"Roy",
        price:516,
        desc:"football it positive program fly ten alone stove dawn satisfied grade one cannot brown apartment noted definition first article aside gas table split writer",
        availablity: true,
    },
    {
        productName:"Garrett",
        price:358,
        desc:"fence speak dinner slight foot elephant pay lucky badly eventually practical wonderful frequently locate freedom cat busy aware dry at broken manufacturing stove bring",
        availablity: true,
    },
    {
        productName:"Louise",
        price:204,
        desc:"several sitting sum cell some sick scientist congress new sort but clean ball tail cool believed boy yet own hill average what soil angry",
        availablity: true,
    },
    {
        productName:"Etta",
        price:454,
        desc:"die action women sad clean sink spite act who industrial chance chart parallel shallow swept black wide think say writing church while door animal",
        availablity: true,
    },
    {
        productName:"Marion",
        price:490,
        desc:"sold love may condition cent am black back rather born sky hang lift neighborhood enjoy apartment do share piece pet watch grew personal beside",
        availablity: true,
    },
    {
        productName:"Elsie",
        price:304,
        desc:"longer understanding outer hour simple drive can ten object buy individual stood telephone hurt another outside father cheese central nice successful clearly facing sentence",
        availablity: true,
    },
    {
        productName:"Mark",
        price:791,
        desc:"hay post coal since putting mighty ants thank valley out run congress west driven copy type pole now figure fifth person discuss lie salmon",
        availablity: true,
    },
    {
        productName:"Charlotte",
        price:530,
        desc:"cowboy drove powerful calm stiff hurt steel suddenly movement battle distant which exact additional planned average tone event production pour level bear beginning wide",
        availablity: true,
    },
    {
        productName:"James",
        price:772,
        desc:"sad pond straw important fuel follow court fifth slip alphabet name firm whatever sang wash height jar paint ten held onto pictured zoo rather",
        availablity: true,
    },
    
];

export default data